api_platform:
    title: Hello API Platform
    version: 1.0.0

    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld:       ['application/ld+json']
        jsonopenapi:  ['application/vnd.openapi+json']
        html:         ['text/html']

    defaults:
        stateless: true

        # ➜ Configuration HTTP Cache / ETag
        cache_headers:
            etag: true
            last_modified: true
            public: true
            max_age: 3600
            shared_max_age: 86400
            vary: ['Content-Type', 'Authorization', 'Origin']

        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true

        pagination_enabled: true
        pagination_items_per_page: 10
        pagination_client_enabled: true
        pagination_client_items_per_page: true

    keep_legacy_inflector: false
    use_symfony_listeners: true
    openapi:
        swagger_ui_extra_configuration:
            persistAuthorization: true
